# -*- coding: utf-8 -*-
"""ICMP_Covert_Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZUvKE5YhRr3WXb62TOXh0StrEYZe_qV

# **ICMP Covert Dataset Generation Script**
"""

#!/usr/bin/env python3
from scapy.all import *
import random
import time
import string

def text_to_binary(text):
    """Convert text to binary string"""
    return ''.join(format(ord(c), '08b') for c in text)

def encode_in_timing(bit):
    """Encode bit in timing: 0 = short delay, 1 = long delay"""
    if bit == '0':
        time.sleep(0.05)  # 50ms
    else:
        time.sleep(0.15)  # 150ms

def generate_stego_packet(target_ip, data, packet_num):
    """Generate ICMP packet with steganography in multiple fields"""

    # Convert data to binary for encoding
    binary_data = text_to_binary(data)

    # 1. Hide data in ICMP ID (16 bits)
    # Use first 16 bits of binary data or random
    if len(binary_data) >= 16:
        icmp_id = int(binary_data[:16], 2)
    else:
        icmp_id = random.randint(1, 65535)

    # 2. Hide data in ICMP Sequence Number (16 bits)
    # Can encode information or use sequential
    if len(binary_data) >= 32:
        icmp_seq = int(binary_data[16:32], 2)
    else:
        icmp_seq = packet_num % 65536

    # 3. Hide data in Payload
    payload_data = data + "_" + str(packet_num)

    # 4. Packet Size Variation (pad payload to vary size)
    padding_size = random.choice([0, 8, 16, 32, 64, 128, 256])
    padding = ''.join(random.choices(string.ascii_letters + string.digits, k=padding_size))
    full_payload = payload_data + padding

    # Create packet
    packet = IP(dst=target_ip)/ICMP(id=icmp_id, seq=icmp_seq)/Raw(load=full_payload)

    return packet

def generate_stego_dataset(target_ip, num_packets=20000, output_file="icmp_stego_dataset.pcap"):
    """Generate complete steganography dataset"""

    print(f"Generating {num_packets} ICMP steganography packets...")
    print(f"Target: {target_ip}")
    print(f"Output: {output_file}")
    print("\nSteganography techniques used:")
    print("  - ICMP ID field")
    print("  - ICMP Sequence number")
    print("  - Payload data")
    print("  - Packet size variation")
    print("  - Inter-packet timing\n")

    # Sample secret messages to hide
    secret_messages = [
        "SECRET", "HIDDEN", "STEALTH", "COVERT", "CONFIDENTIAL",
        "CLASSIFIED", "PRIVATE", "ENCRYPTED", "SECURE", "PROTECTED",
        "SENSITIVE", "RESTRICTED", "TOP_SECRET", "UNDERCOVER", "CLANDESTINE"
    ]

    packets = []

    for i in range(num_packets):
        # Select random message
        message = random.choice(secret_messages)

        # Generate packet with stego
        packet = generate_stego_packet(target_ip, message, i)
        packets.append(packet)

        # 5. Timing-based steganography
        # Vary inter-packet delays to encode information
        timing_patterns = [0.01, 0.02, 0.05, 0.1, 0.15, 0.2]  # seconds
        delay = random.choice(timing_patterns)

        # Send packet (uncomment to actually send)
        # send(packet, verbose=0)
        # time.sleep(delay)

        # Progress indicator
        if (i + 1) % 1000 == 0:
            print(f"Generated {i + 1}/{num_packets} packets...")

    # Save all packets to pcap file
    wrpcap(output_file, packets)
    print(f"\n✓ Successfully generated {num_packets} packets")
    print(f"✓ Saved to: {output_file}")

    # Generate statistics
    print("\n--- Dataset Statistics ---")
    payload_sizes = [len(pkt[Raw].load) if Raw in pkt else 0 for pkt in packets]
    print(f"Payload sizes: min={min(payload_sizes)}, max={max(payload_sizes)}, avg={sum(payload_sizes)/len(payload_sizes):.2f}")

    icmp_ids = [pkt[ICMP].id for pkt in packets]
    print(f"ICMP IDs: min={min(icmp_ids)}, max={max(icmp_ids)}")

    icmp_seqs = [pkt[ICMP].seq for pkt in packets]
    print(f"ICMP Sequences: min={min(icmp_seqs)}, max={max(icmp_seqs)}")

if __name__ == "__main__":
    # Configuration
    TARGET_IP = "192.168.1.100"  # Change to your Ubuntu VM IP
    NUM_PACKETS = 20000
    OUTPUT_FILE = "icmp_stego_20k.pcap"

    # Generate dataset
    generate_stego_dataset(TARGET_IP, NUM_PACKETS, OUTPUT_FILE)

    print("\n--- How to use ---")
    print("1. On Ubuntu VM, capture with:")
    print("   sudo tcpdump -i eth0 icmp -w capture.pcap")
    print("\n2. To actually send packets, uncomment the send() line in the script")
    print("\n3. Analyze with: tshark -r icmp_stego_20k.pcap")