# -*- coding: utf-8 -*-
"""TCP_Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GU4InlHZml3fthmTmlInzSkuX2Wful6

# **TCP Script for Covert Dataset Generation**
"""

#!/usr/bin/env python3
From scapy.all import *
Import random
Import time

TARGET_IP = “192.168.1.100”
TARGET_PORT = 8080
NUM_FLOWS = 100  # Create multiple flows
PACKETS_PER_FLOW = 300  # 30,000 total packets

Def create_realistic_tcp_flow(flow_id):
    “””Create a complete TCP flow with handshake”””

    Src_port = random.randint(10000, 65000)
    Seq_base = random.randint(1000000, 100000000)

    Packets = []

    # 1. SYN (handshake start)
    Pkt = IP(dst=TARGET_IP)/TCP(sport=src_port, dport=TARGET_PORT,
                                 Flags=’S’, seq=seq_base)
    Packets.append(pkt)

    # Simulate handshake delay
    Time.sleep(0.001)

    # 2. Assume SYN-ACK received (we fake it)
    # 3. ACK (handshake complete)
    Pkt = IP(dst=TARGET_IP)/TCP(sport=src_port, dport=TARGET_PORT,
                                 Flags=’A’, seq=seq_base+1, ack=random.randint(1000, 10000))
    Packets.append(pkt)

    # 4. Data transfer with steganography
    For i in range(PACKETS_PER_FLOW – 4):  # -4 for handshake/teardown

        # Your steganography techniques here
        Data_byte = flow_id % 256  # Encode flow ID
        Technique = i % 5

        If technique == 0:
            Seq = seq_base + i*100 + ((data_byte & 0xF0) << 20)
            Pkt = IP(dst=TARGET_IP)/TCP(sport=src_port, dport=TARGET_PORT,
                                         Flags=’PA’, seq=seq)/Raw(load=b’X’*random.randint(50,150))

        Elif technique == 1:
            Window = 8192 + (data_byte % 256)
            Pkt = IP(dst=TARGET_IP)/TCP(sport=src_port, dport=TARGET_PORT,
                                         Flags=’PA’, seq=seq_base+i*100,
                                         Window=window)/Raw(load=b’Y’*random.randint(50,150))

        Else:
            Pkt = IP(dst=TARGET_IP)/TCP(sport=src_port, dport=TARGET_PORT,
                                         Flags=’PA’, seq=seq_base+i*100)/Raw(load=b’Z’*random.randint(50,150))

        Packets.append(pkt)
        Time.sleep(random.uniform(0.001, 0.05))  # Realistic timing

    # 5. FIN (connection teardown)
    Pkt = IP(dst=TARGET_IP)/TCP(sport=src_port, dport=TARGET_PORT,
                                 Flags=’FA’, seq=seq_base+PACKETS_PER_FLOW*100)
    Packets.append(pkt)

    Return packets

Def generate_multiple_flows():
    #Generate realistic multi-flow traffic
    All_packets = []

    For flow_id in range(NUM_FLOWS):
        Print(f”[+] Generating flow {flow_id+1}/{NUM_FLOWS}”)
        Flow_packets = create_realistic_tcp_flow(flow_id)
        All_packets.extend(flow_packets)

        # Random inter-flow gap
        Time.sleep(random.uniform(0.1, 1.0))

    Return all_packets

If __name__ == “__main__”:
    Print(“=”*60)
    Print(“Multi-Flow TCP Steganography Generator”)
    Print(“=”*60)

    Packets = generate_multiple_flows()

    Print(f”\n[+] Generated {len(packets)} packets across {NUM_FLOWS} flows”)
    Wrpcap(“multi_flow_stego.pcap”, packets)
    Print(“[+] Saved to multi_flow_stego.pcap”)

    Input(“\n[?] Press Enter to send...”)

    For i, pkt in enumerate(packets):
        Send(pkt, verbose=False)
        If (i+1) % 500 == 0:
            Print(f”[+] Sent {i+1}/{len(packets)}”)

## Now You Get:

#Flow-Level Features:
#
# Flow 1: (Kali:10234 → Ubuntu:8080)
# - Duration: 15 seconds
# - Packets: 300 (forward only, but realistic)
# - Flags: SYN(1), ACK(298), FIN(1)
# - Avg IAT: 50ms
# - Payload variance: High (steganography)

# Flow 2: (Kali:10235 → Ubuntu:8080)
# - Duration: 12 seconds
# - Packets: 300

#100 flows total