# -*- coding: utf-8 -*-
"""UDP Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v1wMl978KvB290i7v-AeyyrQUTqhKHCU

# **UDP Script for Covert Dataset Generation**

# **For Sender Side**
"""

#!/usr/bin/env python3
import socket
import time
import random

# Configuration - USE YOUR UBUNTU IP!
TARGET_IP = "192.168.8.131"  # ← CHANGE THIS!
BASE_PORT = 9999
NUM_PACKETS = 100000

print("="*60)
print("UDP STEGANOGRAPHY SENDER")
print("="*60)
print(f"Target: {TARGET_IP}")
print(f"Base Port: {BASE_PORT}")
print(f"Packets: {NUM_PACKETS}")
print("\nSteganography techniques:")
print("  ✓ Payload LSB")
print("  ✓ Port variation (9900-10099)")
print("  ✓ Timing (1-50ms delays)")
print("  ✓ Packet size variation")
print("="*60)

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

sent = 0
try:
    for i in range(NUM_PACKETS):
        # PAYLOAD STEGO: Embed hidden data in payload
        hidden_data = i % 256
        base_msg = f"PKT_{i:06d}".encode()

        # LSB substitution in payload
        payload = bytearray(base_msg + b'\00' * 40)
        for bit_pos in range(8):
            bit = (hidden_data >> bit_pos) & 1
            payload[bit_pos] = (payload[bit_pos] & 0xFE) | bit

        # PORT STEGO: Vary destination port (9900-10099)
        port_offset = hidden_data % 200
        dst_port = 9900 + port_offset

        # TIMING STEGO: Variable delay (1-50ms)
        delay = (1 + (hidden_data % 50)) / 1000.0

        # Send packet
        sock.sendto(bytes(payload), (TARGET_IP, dst_port))
        sent += 1

        # Progress
        if (i + 1) % 1000 == 0:
            print(f"[+] Sent {i + 1}/{NUM_PACKETS} packets")

        time.sleep(delay)

except KeyboardInterrupt:
    print(f"\n[!] Stopped by user")
finally:
    print(f"\n[*] Total sent: {sent} packets")
    sock.close()

"""# **For Receiving side:**

"""

#!/usr/bin/env python3
import socket
import time
from datetime import datetime

print("="*60)
print("UDP STEGANOGRAPHY RECEIVER")
print("="*60)
print("Listening on ports: 9900-10099")
print("Expected packets: 10000")
print("="*60)
print("\n*** START WIRESHARK NOW! ***")
print("Filter: udp portrange 9900-10099\n")
input("Press Enter when Wireshark is capturing...")

# Create sockets for multiple ports
sockets = []
ports = list(range(9900, 10100, 5))  # Listen on every 5th port

for port in ports:
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.bind(('0.0.0.0', port))
        sock.settimeout(0.01)  # 10ms timeout
        sockets.append((sock, port))
        print(f"[+] Listening on port {port}")
    except Exception as e:
        print(f"[!] Port {port} failed: {e}")

print(f"\n[*] Ready with {len(sockets)} listeners")
print("[*] Waiting for packets...\n")

received = 0
start_time = time.time()
prev_time = None
port_stats = {}

try:
    while received < 100000:
        for sock, port in sockets:
            try:
                data, addr = sock.recvfrom(4096)
                current_time = time.time()
                received += 1

                # Track port usage
                port_stats[port] = port_stats.get(port, 0) + 1

                # Calculate inter-arrival time
                if prev_time:
                    delay = (currenttime - prev_time) * 1000
                else:
                    delay = 0
                prev_time = current_time

                # Show first few packets
                if received <= 10:
                    print(f"Packet {received}: Port={port}, Size={len(data)}B, Delay={delay:.2}ms")

                # Progress
                if received % 1000 == 0:
                    elapsed = current_time - start_time
                    rate = received / elapsed
                    print(f"[+] Received {received}/10000 ({rate.1f} pkt/s)")

            except socket.timeout:
                continue

except KeyboardInterrupt:
    print("\n[!] Stopped by user")
finally:
    elapsed = time.time() - start_time
    print("\n" + "="*60)
    print(f"[*] Total received: {received} packets")
    print(f"[*] Time: {elapsed:.2f} seconds")
    print(f"[*] Rate: {received/elapsed:.2f} pkt/s")
    print(f"\n[*] Unique ports used: {len(port_stats)}")
    print(f"[*] Port distribution: {list(port_stats.keys())[:10]}...")
    print("="*60)
    print("\n*** STOP WIRESHARK AND SAVE AS .pcapng ***")

    for sock, _ in sockets:
        sock.close()